regions:
  standard:
    level-requirement: 0
    region:
      region-type: RECTANGLE
      world: darkzone
      min-x: -500
      max-x: 500
      min-z: -500
      max-z: 500

levels:
  'level-1':
    xp-required: 0
    display-name: 'Adventurer'
  'level-2':
    xp-required: 1000
    display-name: 'Ender'
  'level-3':
    xp-required: 2500
    display-name: 'Dark Teleporter'
  'level-4':
    xp-required: 10000
    display-name: 'Void Master'

# Use the same keys here from the drop-tables section in entities.yml
item-worths:
  'enderpearl':
    vault-currency: 500.0
    darkzone-currency: 10